Lint command pipeline

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -38,13 +38,19 @@ jobs:
         id: get-changed-files
         run: |
           git fetch origin
-          git fetch upstream
+
+          # Check if upstream exists (forked repo) and add it if it doesn't exist
+          if ! git remote get-url upstream &>/dev/null; then
+            echo "Upstream not found, skipping upstream fetch"
+          else
+            git fetch upstream
+          fi
 
           echo "Base branch: $GITHUB_BASE_REF"
           echo "Head branch: $GITHUB_HEAD_REF"
 
           # Use the correct references to compare the base and head commits
-          changed_files=$(git diff --name-only upstream/$GITHUB_BASE_REF...$GITHUB_HEAD_REF)
+          changed_files=$(git diff --name-only origin/$GITHUB_BASE_REF...$GITHUB_HEAD_REF)
           echo "Changed files: $changed_files"
 
           # Convert list of files to a single line, space-separated
@@ -57,7 +63,6 @@ jobs:
         run: |
           git show ${{ github.event.pull_request.base.sha }}
           git show ${{ github.event.pull_request.head.sha }}
-
 
       - name: Lint packages
         run: |
