Lint command pipeline

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -52,36 +52,52 @@ jobs:
           # Set it as an environment variable for later use
           echo "changed_files=$changed_files" >> $GITHUB_ENV
 
-      - name: debug - Check if the binary exists
+      - name: Debug Check the binary location
         run: |
-          ls -l ~/stanctl-integration
-          file ~/stanctl-integration
+          echo "Path to binary: $HOME/stanctl-integration"
+          ls -l $HOME/stanctl-integration
+          file $HOME/stanctl-integration
+
+      - name: Debug Run the binary directly
+        run: |
+          echo "Running binary directly"
+          $HOME/stanctl-integration
+          $HOME/stanctl-integration --version || echo "Failed to get version"
+          $HOME/stanctl-integration --help || echo "Failed to show help"
 
       - name: Lint packages
         run: |
-          changed_files="${{ env.changed_files }}"
-            
-          # Debug: Check the contents of the changed files
-          echo "Changed files: $changed_files"
-            
-          # Loop over each directory and check if it has changes
-          for dir in packages/@instana-integration/*; do
-            if [ -d "$dir" ]; then
-              if echo "$changed_files" | grep -q "$dir"; then
-                echo "Linting package: $dir"
-                cd "$dir"
-                echo "Running lint command: ~/stanctl-integration lint --debug --strict-mode"
-                echo ~/stanctl-integration --version
-                ~/stanctl-integration lint --debug --strict-mode
-                if [ $? -eq 0 ]; then
-                  echo "Linting successful for $dir"
-                else
-                  echo "Error: Linting failed for $dir"
-                fi
-                cd -
-              else
-                echo "No changes in $dir, skipping lint"
-              fi
-            fi
-          done
+          echo "Running lint command: $HOME/stanctl-integration lint --debug --strict-mode"
+          $HOME/stanctl-integration lint --debug --strict-mode || echo "Error executing lint command. Exit code: $?"
+
+
+#
+#
+#      - name: Lint packages
+#        run: |
+#          changed_files="${{ env.changed_files }}"
+#
+#          # Debug: Check the contents of the changed files
+#          echo "Changed files: $changed_files"
+#
+#          # Loop over each directory and check if it has changes
+#          for dir in packages/@instana-integration/*; do
+#            if [ -d "$dir" ]; then
+#              if echo "$changed_files" | grep -q "$dir"; then
+#                echo "Linting package: $dir"
+#                cd "$dir"
+#                echo "Running lint command: ~/stanctl-integration lint --debug --strict-mode"
+#                echo ~/stanctl-integration --version
+#                ~/stanctl-integration lint --debug --strict-mode
+#                if [ $? -eq 0 ]; then
+#                  echo "Linting successful for $dir"
+#                else
+#                  echo "Error: Linting failed for $dir"
+#                fi
+#                cd -
+#              else
+#                echo "No changes in $dir, skipping lint"
+#              fi
+#            fi
+#          done
 
