Lint command pipeline

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -29,6 +29,10 @@ jobs:
       - name: Download stanctl-integration binary
         run: |
           curl -L https://github.com/instana/observability-as-code/releases/download/stanctl-configuration-v1.3.0/stanctl-integration-linux -o ~/stanctl-integration
+          if [ ! -f ~/stanctl-integration ]; then
+            echo "Error: stanctl-integration binary not found!"
+            exit 1
+          fi
           chmod +x ~/stanctl-integration
 
       - name: Add stanctl-integration to PATH
